// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHJlcZaNo4pHzGNwtwWglgKgJyV31pzw0',
    appId: '1:77009832062:web:1e0afada4efacbfa96b02f',
    messagingSenderId: '77009832062',
    projectId: 'teamsync-c7f10',
    authDomain: 'teamsync-c7f10.firebaseapp.com',
    storageBucket: 'teamsync-c7f10.appspot.com',
    measurementId: 'G-LN68PLYWN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy6F-GgCB7xOju_nVqsLA6LlSOkiCNLzE',
    appId: '1:77009832062:android:53856a64be10d6ae96b02f',
    messagingSenderId: '77009832062',
    projectId: 'teamsync-c7f10',
    storageBucket: 'teamsync-c7f10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATkx57kHA6NSiPK3po2ov0YmFfOawev_4',
    appId: '1:77009832062:ios:05565a148c2e985896b02f',
    messagingSenderId: '77009832062',
    projectId: 'teamsync-c7f10',
    storageBucket: 'teamsync-c7f10.appspot.com',
    iosBundleId: 'com.example.team',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATkx57kHA6NSiPK3po2ov0YmFfOawev_4',
    appId: '1:77009832062:ios:05565a148c2e985896b02f',
    messagingSenderId: '77009832062',
    projectId: 'teamsync-c7f10',
    storageBucket: 'teamsync-c7f10.appspot.com',
    iosBundleId: 'com.example.team',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHJlcZaNo4pHzGNwtwWglgKgJyV31pzw0',
    appId: '1:77009832062:web:4f52536c10b405ef96b02f',
    messagingSenderId: '77009832062',
    projectId: 'teamsync-c7f10',
    authDomain: 'teamsync-c7f10.firebaseapp.com',
    storageBucket: 'teamsync-c7f10.appspot.com',
    measurementId: 'G-895VHWNT5L',
  );
}
