import 'project.dart';

final List<Project> projects = [
  Project(
    leaderUid: 'uid1',
    title: '모앱개 앱 팀플',
    duration: '24.03.13 - 24.06.21',
    members: 5,
    description: '모바일 애플리케이션 개발 팀 프로젝트입니다.',
    progress: 0.41,
    isCompleted: false,
  ),
  Project(
    leaderUid: 'uid2',
    title: '웹 개발 프로젝트',
    duration: '24.01.10 - 24.04.20',
    members: 4,
    description: '웹 애플리케이션 개발 프로젝트입니다.',
    progress: 0.75,
    isCompleted: false,
  ),
  Project(
    leaderUid: 'uid3',
    title: '데이터 분석 프로젝트',
    duration: '23.11.15 - 24.02.28',
    members: 3,
    description: '데이터 분석 및 시각화 프로젝트입니다.',
    progress: 1.0,
    isCompleted: true,
  ),
  Project(
    leaderUid: 'uid4',
    title: '인공지능 연구 프로젝트',
    duration: '24.05.01 - 24.08.30',
    members: 6,
    description: '인공지능 알고리즘 연구 및 개발 프로젝트입니다.',
    progress: 0.30,
    isCompleted: false,
  ),
  Project(
    leaderUid: 'uid5',
    title: 'IoT 시스템 구축',
    duration: '23.09.01 - 24.12.31',
    members: 8,
    description: '사물인터넷(IoT) 시스템 구축 프로젝트입니다.',
    progress: 1.00,
    isCompleted: true,
  ),
  Project(
    leaderUid: 'uid6',
    title: '블록체인 기반 애플리케이션',
    duration: '24.06.01 - 24.09.30',
    members: 7,
    description: '블록체인 기술을 활용한 애플리케이션 개발 프로젝트입니다.',
    progress: 0.20,
    isCompleted: false,
  ),
  Project(
    leaderUid: 'uid7',
    title: '자연어 처리 연구',
    duration: '24.07.01 - 24.10.31',
    members: 5,
    description: '자연어 처리(NLP) 알고리즘 연구 프로젝트입니다.',
    progress: 0.50,
    isCompleted: false,
  ),
];
